apiVersion: v1
kind: Pod
metadata:
  labels:
    product-group: ui
spec:
  containers:
  - name: jnlp
    tty: true
    image: jenkinsci/jnlp-slave:alpine
  - name: docker-builder
    image: gcr.io/kaniko-project/executor:debug
    command:
    - /busbox/cat
    tty: true
  - name: json-lint
    image: sahsu/docker-jsonlint:latest
    command:
    - cat
    tty: true